### ISSUE TITLE
add custom class

### ISSUE THREAD

**Issue by cgnieder** [LaTeXMusicSheets/LeadsheetArchive#149]
I noticed you have a modified version of `leadsheet.cls` which is part of my `leadsheets` package. This is fine (and [indeed LPPL explicitly allows you to](https://www.latex-project.org/lppl/) for private uses – if you distribute it then there are a few points to pay attention to) but I'd consider the following:

should I ever update the original you won't either not notice as your workflow will just use your modified copy or you will have to update your modified version accordingly. Instead I'd suggest to create a wrapper class which can then include the necessary modifications…

**Comment by JosuaHaug** [comment]
New document class has been introduced to adress custom changes for own verse types and design.
