### ISSUE TITLE
Offering (Christmas)

### ISSUE THREAD

**Issue by JosuaHaug** [LaTeXMusicSheets/LeadsheetArchive#50]

**Comment by JosuaHaug** [comment]
Added lyrics with 794ddf66dd444574418f5cdabe854c289f250774

**Comment by JosuaHaug** [comment]
Added lyrics with 794ddf66dd444574418f5cdabe854c289f250774

**Comment by nivekznews** [comment]
@JosuaHaug Schau dir das Outro bitte noch an
